services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: vibeton_db
      POSTGRES_USER: vibeton_user
      POSTGRES_PASSWORD: vibeton_password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U vibeton_user -d vibeton_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: vibeton_user
      DB_PASS: vibeton_password
      DB_NAME: vibeton_db
      DB_SSLMODE: disable
      SERVER_PORT: 8000
      SERVER_HOST: 0.0.0.0
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
